### ISSUE TITLE
Error with https://www.bobbysebolao.com

### ISSUE THREAD

**Issue by bobbysebolao** [remy/wm#9]
URL: https://www.bobbysebolao.com
Status: 200
Error: `No webmention endpoints found in the 1 content entry`

**Comment by remy** [comment]
@bobbysebolao can you point me to where you think the webmention should be (on your site)?

**Comment by bobbysebolao** [comment]
Hi @remy , yes I have an ```h-entry``` section on my home page (index.html, line 540). It's set to ```display: none```, links to https://aaronpk.com/reply.html

**Comment by remy** [comment]
I'm just poking around before hitting the hay, but I've found two things. The first is in the structure of your (valid) microformat marked up content. Somehow, the `wm` logic isn't picking it up correctly. I've got a working fix offline for that which I'll push when it's not late!

The second issue is that you're pointing to a 404, so the webmention would never land anyway. I'm seeing this when I follow a curl request (and IIRC I can't send a mention to a 404 - from the spec…though it's late and I could be wrong):

```
curl -I https://aaronpk.com/reply.html -X GET -L                                                                   ● ■■■■■■■■■■
HTTP/1.1 302 Found
Server: nginx/1.14.0
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Cache-Control: no-cache
Date: Sat, 03 Aug 2019 23:08:14 GMT
Location: https://aaronparecki.com/reply.html

HTTP/1.1 404 Not Found
Server: nginx/1.14.0
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Cache-Control: no-cache
Link: <https://switchboard.p3k.io/>; rel="hub"
Link: <https://aaronparecki.com/auth/token>; rel="token_endpoint"
Link: <https://aaronparecki.com/reply.html>; rel="self"
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Authorization,Content-Type,Accept,Referer,Origin,User-Agent,Cache-Control,Pragma
Date: Sat, 03 Aug 2019 23:08:15 GMT
```

**Comment by bobbysebolao** [comment]
Thanks for pointing out that 404 response. I've changed the webmention target URL to the correct one (https://aaronparecki.com/2018/06/30/11/your-first-webmention)  - this now sends successfully.

Interesting, I look forward to the ```wm``` logic fix! What you have done with this tool is great, thank you.

**Comment by remy** [comment]
I've pushed this fix, but I don't think your webmention is in place anymore… I can't recall whether webmentions are supposed to follow `u-in-reply-to` links or not…

**Comment by bobbysebolao** [comment]
Hi Remy, I think it is an issue with your tool's webmention discovery. [xray.p3k.io](https://xray.p3k.io/) identifies the webmention on my homepage, but when I run it through your tool I still get the same error:

![Screen Shot 2019-08-05 at 12 06 41](https://user-images.githubusercontent.com/30030755/62460296-8d3cab00-b779-11e9-9839-60ec07ad91e6.png)

**Comment by remy** [comment]
Properly fixed now! Thanks for your help.

**Comment by bobbysebolao** [comment]
Happy to help!
